// services/elicitations/create-elicitation.service.js

const mongoose = require("mongoose");
const { ProjectModel } = require("@models/project.model");
const { ElicitationModel } = require("@models/elicitation.model");
const { Phases } = require("@configs/enums.config");
const { createPhaseWithVersionManagement } = require("@services/common/phase-management.service");
const { logActivityTrackerEvent } = require("@services/audit/activity-tracker.service");
const { ACTIVITY_TRACKER_EVENTS } = require("@configs/tracker.config");
const { prepareAuditData } = require("@utils/audit-data.util");
const { logWithTime } = require("@utils/time-stamps.util");
const { CONFLICT, NOT_FOUND, INTERNAL_ERROR } = require("@configs/http-status.config");

/**
 * Creates a new elicitation document in the database.
 *
 * @param {Object} params
 * @param {string} params.projectId              - Project MongoDB ObjectId
 * @param {string} params.mode                   - Elicitation mode (OPEN or FAST)
 * @param {boolean} [params.allowParallelMeetings] - Allow parallel meetings (default: false)
 * @param {string} params.createdBy              - Admin USR ID
 * @param {Object} params.auditContext           - { user, device, requestId }
 *
 * @returns {{ success: true, elicitation } | { success: false, message, errorCode }}
 */
const createElicitationService = async ({
  projectId,
  mode,
  allowParallelMeetings,
  createdBy,
  auditContext
}) => {
  try {
    // ── Step 1: Verify project exists ──────────────────────────────────
    const project = await ProjectModel.findById(projectId);
    if (!project) {
      logWithTime(`❌ [createElicitationService] Project not found: ${projectId}`);
      return { success: false, message: "Project not found", errorCode: NOT_FOUND };
    }

    // ── Step 2: Check if elicitation already exists ───────────────────
    const existingElicitation = await ElicitationModel.findOne({
      projectId,
      isDeleted: false,
      isFrozen: false
    });

    if (existingElicitation) {
      logWithTime(`❌ [createElicitationService] Elicitation already exists for project ${projectId}`);
      return { success: false, message: "An active elicitation already exists for this project", errorCode: CONFLICT };
    }

    // ── Step 3: Update project's currentPhase to ELICITATION ─────────
    logWithTime(`[createElicitationService] Updating project phase to ELICITATION for ${projectId}`);
    
    const oldProjectData = { ...project.toObject ? project.toObject() : project };
    
    const updatedProject = await ProjectModel.findByIdAndUpdate(
      projectId,
      {
        currentPhase: Phases.ELICITATION
        // Agar project level minorVersion increment karni hai, toh yahan: $inc: { minorVersion: 1 } add karo
      },
      { new: true }
    );

    if (!updatedProject) {
      logWithTime(`❌ [createElicitationService] Failed to update project phase`);
      return { success: false, message: "Failed to update project phase", errorCode: INTERNAL_ERROR };
    }

    // Log project update activity
    const { user, device, requestId } = auditContext || {};
    const { oldData, newData } = prepareAuditData(oldProjectData, updatedProject);
    logActivityTrackerEvent(
      user, device, requestId, ACTIVITY_TRACKER_EVENTS.UPDATE_PROJECT,
      `Project phase transitioned to ELICITATION`, // Removed the fake minorVersion log
      { oldData, newData, adminActions: { targetId: projectId } }
    );

    // ── Step 4: Create phase WITH version management AND additional data ─
    logWithTime(`[createElicitationService] Creating ELICITATION phase document`);
    
    // Pass both mode and allowParallelMeetings to the phase management service
    const phaseResult = await createPhaseWithVersionManagement({
      project: updatedProject,
      createdBy,
      auditContext,
      additionalData: { 
        elicitationMode: mode,
        allowParallelMeetings: allowParallelMeetings || false
      }
    });

    if (!phaseResult.success) {
      logWithTime(`❌ [createElicitationService] Failed to create phase: ${phaseResult.message}`);
      
      // OPTIONAL BUT RECOMMENDED: Agar phase banne mein error aaye, 
      // toh Project ka phase wapas Inception par revert karne ka logic yahan likh sakte ho (Manual Rollback).
      
      return {
        success: false,
        message: phaseResult.message,
        errorCode: phaseResult.errorCode || INTERNAL_ERROR
      };
    }

    // ── Step 5: DELETED! (Because phaseResult.phase ALREADY contains the new document) ──

    logWithTime(`✅ [createElicitationService] Elicitation created with ID: ${phaseResult.phase._id} and mode: ${mode}`);
    
    // Return the phase generated by our common service
    return { success: true, elicitation: phaseResult.phase };

  } catch (error) {
    logWithTime(`❌ [createElicitationService] Error: ${error.message}`);
    if (error.name === "ValidationError") {
      return { success: false, message: "Validation error", error: error.message };
    }
    return { success: false, message: "Internal error while creating elicitation", error: error.message };
  }
};

module.exports = { createElicitationService };