// services/elicitations/create-elicitation.service.js

const { ProjectModel } = require("@models/project.model");
const { ElicitationModel } = require("@models/elicitation.model");
const { Phases, WorkflowModes, RequirementGovernanceModes } = require("@configs/enums.config");
const { createPhaseWithVersionManagement } = require("@services/common/phase-management.service");
const { logWithTime } = require("@utils/time-stamps.util");
const { CONFLICT, NOT_FOUND, INTERNAL_ERROR } = require("@configs/http-status.config");

/**
 * Creates a new elicitation document in the database.
 *
 * @param {Object} params
 * @param {string} params.projectId                    - Project MongoDB ObjectId
 * @param {string} [params.workflowMode]               - Workflow mode (OPEN or MODERATION, default: OPEN)
 * @param {string} [params.requirementGovernanceMode]  - Governance mode (PHASE | CREATED_IN_MODE | STRICT, default: PHASE)
 * @param {boolean} [params.allowParallelMeetings]     - Allow parallel meetings (default: false)
 * @param {string} params.createdBy                    - Admin USR ID
 * @param {Object} params.auditContext                 - { user, device, requestId }
 *
 * @returns {{ success: true, elicitation } | { success: false, message, errorCode }}
 */
const createElicitationService = async ({
  projectId,
  workflowMode,
  requirementGovernanceMode,
  allowParallelMeetings,
  createdBy,
  auditContext
}) => {
  try {
    // ── Step 1: Verify project exists ──────────────────────────────────
    const project = await ProjectModel.findById(projectId);
    if (!project) {
      logWithTime(`❌ [createElicitationService] Project not found: ${projectId}`);
      return { success: false, message: "Project not found", errorCode: NOT_FOUND };
    }

    // ── Step 2: Check if elicitation already exists ───────────────────
    const existingElicitation = await ElicitationModel.findOne({
      projectId,
      isDeleted: false,
      isFrozen: false
    });

    if (existingElicitation) {
      logWithTime(`❌ [createElicitationService] Elicitation already exists for project ${projectId}`);
      return { success: false, message: "An active elicitation already exists for this project", errorCode: CONFLICT };
    }

    // ── Step 3: Update project's currentPhase to ELICITATION ─────────
    logWithTime(`[createElicitationService] Updating project phase to ELICITATION for ${projectId}`);

    // ── Step 4: Create phase WITH version management AND additional data ─
    logWithTime(`[createElicitationService] Creating ELICITATION phase document`);
    
    // Pass both mode and allowParallelMeetings to the phase management service
    const phaseResult = await createPhaseWithVersionManagement({
      project,
      targetPhase: Phases.ELICITATION,
      createdBy,
      auditContext,
      additionalData: { 
        workflowMode: workflowMode || WorkflowModes.OPEN,
        requirementGovernanceMode: requirementGovernanceMode || RequirementGovernanceModes.PHASE,
        allowParallelMeetings: allowParallelMeetings || false
      }
    });

    if (!phaseResult.success) {
      logWithTime(`❌ [createElicitationService] Failed to create phase: ${phaseResult.message}`);
      
      // OPTIONAL BUT RECOMMENDED: Agar phase banne mein error aaye, 
      // toh Project ka phase wapas Inception par revert karne ka logic yahan likh sakte ho (Manual Rollback).
      
      return {
        success: false,
        message: phaseResult.message,
        errorCode: phaseResult.errorCode || INTERNAL_ERROR
      };
    }

    // ── Step 5: DELETED! (Because phaseResult.phase ALREADY contains the new document) ──

    logWithTime(`✅ [createElicitationService] Elicitation created with ID: ${phaseResult.phase._id} and workflowMode: ${workflowMode || 'OPEN'}`);
    
    // Return the phase generated by our common service
    return { success: true, elicitation: phaseResult.phase };

  } catch (error) {
    logWithTime(`❌ [createElicitationService] Error: ${error.message}`);
    if (error.name === "ValidationError") {
      return { success: false, message: "Validation error", error: error.message };
    }
    return { success: false, message: "Internal error while creating elicitation", error: error.message };
  }
};

module.exports = { createElicitationService };