// services/inceptions/create-inception.service.js

const { ProjectModel } = require("@models/project.model");
const { InceptionModel } = require("@models/inception.model");
const { Phases } = require("@configs/enums.config");
const { createPhaseWithVersionManagement } = require("@services/common/phase-management.service");
const { logWithTime } = require("@utils/time-stamps.util");
const { CONFLICT, NOT_FOUND, INTERNAL_ERROR } = require("@configs/http-status.config");

/**
 * Creates a new inception document in the database.
 *
 * @param {Object} params
 * @param {string} params.projectId              - Project MongoDB ObjectId
 * @param {boolean} [params.allowParallelMeetings] - Allow parallel meetings (default: false)
 * @param {string} params.createdBy              - Admin USR ID
 * @param {Object} params.auditContext           - { user, device, requestId }
 *
 * @returns {{ success: true, inception } | { success: false, message, errorCode }}
 */
const createInceptionService = async ({
  projectId,
  allowParallelMeetings,
  createdBy,
  auditContext
}) => {
  try {
    // ── Step 1: Verify project exists ──────────────────────────────────
    const project = await ProjectModel.findById(projectId);
    if (!project) {
      logWithTime(`❌ [createInceptionService] Project not found: ${projectId}`);
      return { success: false, message: "Project not found", errorCode: NOT_FOUND };
    }

    // ── Step 2: Check if inception already exists ─────────────────────
    const existingInception = await InceptionModel.findOne({
      projectId,
      isDeleted: false,
      isFrozen: false
    });

    if (existingInception) {
      logWithTime(`❌ [createInceptionService] Inception already exists for project ${projectId}`);
      return { success: false, message: "An active inception already exists for this project", errorCode: CONFLICT };
    }

    // ── Step 3: Ensure project is in INCEPTION phase ──────────────────
    // Inception is the starting phase, so project should stay at INCEPTION
    logWithTime(`[createInceptionService] Ensuring project phase is INCEPTION for ${projectId}`);
    
    const oldProjectData = { ...project.toObject ? project.toObject() : project };
    
    const updatedProject = await ProjectModel.findByIdAndUpdate(
      projectId,
      { currentPhase: Phases.INCEPTION },
      { new: true }
    );

    if (!updatedProject) {
      logWithTime(`❌ [createInceptionService] Failed to update project phase`);
      return { success: false, message: "Failed to update project phase", errorCode: INTERNAL_ERROR };
    }

    // ── Step 4: Create phase with version management ──────────────────
    // This handles version management and activity tracking automatically
    logWithTime(`[createInceptionService] Creating INCEPTION phase with version management`);
    const phaseResult = await createPhaseWithVersionManagement({
      project: updatedProject,
      allowParallelMeetings: typeof allowParallelMeetings === 'boolean' ? allowParallelMeetings : false,
      createdBy,
      auditContext
    });

    if (!phaseResult.success) {
      logWithTime(`❌ [createInceptionService] Failed to create phase: ${phaseResult.message}`);
      return {
        success: false,
        message: phaseResult.message,
        errorCode: phaseResult.errorCode || INTERNAL_ERROR
      };
    }

    logWithTime(`✅ [createInceptionService] Inception created with ID: ${phaseResult.phase._id}`);
    
    // Return the phase generated by our common service
    return { success: true, inception: phaseResult.phase };

  } catch (error) {
    logWithTime(`❌ [createInceptionService] Error: ${error.message}`);
    if (error.name === "ValidationError") {
      return { success: false, message: "Validation error", error: error.message };
    }
    return { success: false, message: "Internal error while creating inception", error: error.message };
  }
};

module.exports = { createInceptionService };
