const { DB_COLLECTIONS } = require("./db-collections.config");
const { ACTIVITY_TRACKER_EVENTS } = require("./tracker.config");

// Allowed conversion pairs
const ALLOWED_CONVERSIONS = new Set([
  `${DB_COLLECTIONS.IDEAS}:${DB_COLLECTIONS.SCOPES}`,
  `${DB_COLLECTIONS.IDEAS}:${DB_COLLECTIONS.CONSTRAINTS}`,
  `${DB_COLLECTIONS.IDEAS}:${DB_COLLECTIONS.REQUIREMENTS}`,

  `${DB_COLLECTIONS.SCOPES}:${DB_COLLECTIONS.REQUIREMENTS}`,
  `${DB_COLLECTIONS.SCOPES}:${DB_COLLECTIONS.CONSTRAINTS}`,
  `${DB_COLLECTIONS.SCOPES}:${DB_COLLECTIONS.HIGH_LEVEL_FEATURES}`,

  `${DB_COLLECTIONS.CONSTRAINTS}:${DB_COLLECTIONS.SCOPES}`,
  `${DB_COLLECTIONS.CONSTRAINTS}:${DB_COLLECTIONS.REQUIREMENTS}`,
  `${DB_COLLECTIONS.CONSTRAINTS}:${DB_COLLECTIONS.HIGH_LEVEL_FEATURES}`,

  `${DB_COLLECTIONS.REQUIREMENTS}:${DB_COLLECTIONS.CONSTRAINTS}`,
  `${DB_COLLECTIONS.REQUIREMENTS}:${DB_COLLECTIONS.SCOPES}`,
  `${DB_COLLECTIONS.REQUIREMENTS}:${DB_COLLECTIONS.HIGH_LEVEL_FEATURES}`,
]);

const isConversionAllowed = (sourceCollection, targetCollection) => {
  return ALLOWED_CONVERSIONS.has(
    `${sourceCollection}:${targetCollection}`
  );
};

// Map collections to their precise CREATE and DELETE events
const COLLECTION_EVENT_MAP = {
  [DB_COLLECTIONS.IDEAS]: {
    CREATE: ACTIVITY_TRACKER_EVENTS.CREATE_IDEA,
    DELETE: ACTIVITY_TRACKER_EVENTS.DELETE_IDEA,
  },
  [DB_COLLECTIONS.HIGH_LEVEL_FEATURES]: {
    CREATE: ACTIVITY_TRACKER_EVENTS.CREATE_HLF,
    DELETE: ACTIVITY_TRACKER_EVENTS.DELETE_HLF,
  },
  [DB_COLLECTIONS.REQUIREMENTS]: {
    CREATE: ACTIVITY_TRACKER_EVENTS.REQUIREMENT_CREATED,
    DELETE: ACTIVITY_TRACKER_EVENTS.REQUIREMENT_DELETED,
  },
  [DB_COLLECTIONS.SCOPES]: {
    CREATE: ACTIVITY_TRACKER_EVENTS.CREATE_SCOPE,
    DELETE: ACTIVITY_TRACKER_EVENTS.DELETE_SCOPE,
  },
  [DB_COLLECTIONS.CONSTRAINTS]: {
    CREATE: ACTIVITY_TRACKER_EVENTS.CREATE_CONSTRAINT,
    DELETE: ACTIVITY_TRACKER_EVENTS.DELETE_CONSTRAINT,
  }
};

const getEventsForCollection = (collection) => {
  return COLLECTION_EVENT_MAP[collection] || null;
};

module.exports = {
  ALLOWED_CONVERSIONS,
  isConversionAllowed,
  COLLECTION_EVENT_MAP,
  getEventsForCollection
};
