// configs/entity-mapping.config.js

const { DB_COLLECTIONS } = require("./db-collections.config");

const ENTITY_MAPPING = {
    [DB_COLLECTIONS.HIGH_LEVEL_FEATURES]: "HLF",
    [DB_COLLECTIONS.SCOPES]: "SC",
    [DB_COLLECTIONS.REQUIREMENTS]: "REQ",
    [DB_COLLECTIONS.PROJECTS]: "PROJ",
    [DB_COLLECTIONS.PRODUCT_REQUESTS]: "PR",
    [DB_COLLECTIONS.ORG_PROJECT_REQUESTS]: "OPR",
    [DB_COLLECTIONS.CONSTRAINTS]: "CONST"
};

module.exports = {
    ENTITY_MAPPING
};