module.exports = {
  ACTIVITY_TRACKER_EVENTS: Object.freeze({
    // ========== PROJECT CONTROLLER EVENTS ==========
    CREATE_PROJECT: "CREATE_PROJECT",
    UPDATE_PROJECT: "UPDATE_PROJECT",
    ABORT_PROJECT: "ABORT_PROJECT",
    COMPLETE_PROJECT: "COMPLETE_PROJECT",
    RESUME_PROJECT: "RESUME_PROJECT",
    ARCHIVE_PROJECT: "ARCHIVE_PROJECT",
    DELETE_PROJECT: "DELETE_PROJECT",

    // ========== STAKEHOLDER CONTROLLER EVENTS ==========
    CREATE_STAKEHOLDER: "CREATE_STAKEHOLDER",
    UPDATE_STAKEHOLDER: "UPDATE_STAKEHOLDER",
    DELETE_STAKEHOLDER: "DELETE_STAKEHOLDER",

    // ========== VERSION CONTROL EVENTS ==========
    VERSION_CHANGE: "VERSION_CHANGE",
    ON_HOLD_PROJECT: "ON_HOLD_PROJECT",
    CONVERT_ON_HOLD_TO_ACTIVE: "CONVERT_ON_HOLD_TO_ACTIVE",

    CREATE_INCEPTION: "CREATE_INCEPTION",
    UPDATE_INCEPTION: "UPDATE_INCEPTION"
  }),

  SERVICE_TRACKER_EVENTS: Object.freeze({
    // ========== INTERNAL CONTROLLER EVENTS ==========
    DELETE_INACTIVE_USERS: "DELETE_INACTIVE_USERS",
    
    // ========== SYNC EVENTS ==========
    SYNC_USER_DATA: "SYNC_USER_DATA", 
    SYNC_ADMIN_DATA: "SYNC_ADMIN_DATA",
    SYNC_MY_DATA: "SYNC_MY_DATA",
    
    // ========== SYSTEM EVENTS ==========
    CREATE_SUPER_ADMIN: "CREATE_SUPER_ADMIN",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
    UPDATE_ADMIN_DETAILS: "UPDATE_ADMIN_DETAILS"
  })
};