module.exports = {
  ACTIVITY_TRACKER_EVENTS: Object.freeze({
    // ========== PROJECT CONTROLLER EVENTS ==========
    CREATE_PROJECT: "CREATE_PROJECT",
    UPDATE_PROJECT: "UPDATE_PROJECT",
    ABORT_PROJECT: "ABORT_PROJECT",
    COMPLETE_PROJECT: "COMPLETE_PROJECT",
    RESUME_PROJECT: "RESUME_PROJECT",
    ARCHIVE_PROJECT: "ARCHIVE_PROJECT",
    DELETE_PROJECT: "DELETE_PROJECT",
    ACTIVATE_PROJECT: "ACTIVATE_PROJECT",
    CHANGE_PROJECT_OWNER: "CHANGE_PROJECT_OWNER",

    // ========== STAKEHOLDER CONTROLLER EVENTS ==========
    CREATE_STAKEHOLDER: "CREATE_STAKEHOLDER",
    UPDATE_STAKEHOLDER: "UPDATE_STAKEHOLDER",
    DELETE_STAKEHOLDER: "DELETE_STAKEHOLDER",

    // ========== SCOPE CONTROLLER EVENTS ==========
    CREATE_SCOPE: "CREATE_SCOPE",
    UPDATE_SCOPE: "UPDATE_SCOPE",
    DELETE_SCOPE: "DELETE_SCOPE",
    LINK_SCOPE_TO_HLF: "LINK_SCOPE_TO_HLF",
    UNLINK_SCOPE_TO_HLF: "UNLINK_SCOPE_TO_HLF",

    // ========== CONSTRAINT CONTROLLER EVENTS ==========
    CREATE_CONSTRAINT: "CREATE_CONSTRAINT",
    UPDATE_CONSTRAINT: "UPDATE_CONSTRAINT",
    DELETE_CONSTRAINT: "DELETE_CONSTRAINT",
    LINK_CONSTRAINT_TO_HLF: "LINK_CONSTRAINT_TO_HLF",
    UNLINK_CONSTRAINT_TO_HLF: "UNLINK_CONSTRAINT_TO_HLF",

    // ========== HIGH-LEVEL FEATURE CONTROLLER EVENTS ==========
    CREATE_HLF: "CREATE_HLF",
    UPDATE_HLF: "UPDATE_HLF",
    DELETE_HLF: "DELETE_HLF",
    LINK_HLF_TO_IDEA: "LINK_HLF_TO_IDEA",

    // ========== PRODUCT VISION CONTROLLER EVENTS ==========
    CREATE_PRODUCT_VISION: "CREATE_PRODUCT_VISION",
    UPDATE_PRODUCT_VISION: "UPDATE_PRODUCT_VISION",
    DELETE_PRODUCT_VISION: "DELETE_PRODUCT_VISION",

    // ========== PRODUCT REQUEST CONTROLLER EVENTS ==========
    CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
    UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
    APPROVE_PRODUCT_REQUEST: "APPROVE_PRODUCT_REQUEST",
    REJECT_PRODUCT_REQUEST: "REJECT_PRODUCT_REQUEST",
    DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
    CANCEL_PRODUCT_REQUEST: "CANCEL_PRODUCT_REQUEST",

    // ========== ORG PROJECT REQUEST EVENTS ==========
    CREATE_ORG_PROJECT_REQUEST: "CREATE_ORG_PROJECT_REQUEST",
    UPDATE_ORG_PROJECT_REQUEST: "UPDATE_ORG_PROJECT_REQUEST",
    APPROVE_ORG_PROJECT_REQUEST: "APPROVE_ORG_PROJECT_REQUEST",
    REJECT_ORG_PROJECT_REQUEST: "REJECT_ORG_PROJECT_REQUEST",
    WITHDRAW_ORG_PROJECT_REQUEST: "WITHDRAW_ORG_PROJECT_REQUEST",

    // ========== VERSION CONTROL EVENTS ==========
    VERSION_CHANGE: "VERSION_CHANGE",
    PHASE_VERSION_CHANGE: "PHASE_VERSION_CHANGE",
    ON_HOLD_PROJECT: "ON_HOLD_PROJECT",
    CONVERT_ON_HOLD_TO_ACTIVE: "CONVERT_ON_HOLD_TO_ACTIVE",

    CREATE_INCEPTION: "CREATE_INCEPTION",
    UPDATE_INCEPTION: "UPDATE_INCEPTION",
    DELETE_INCEPTION: "DELETE_INCEPTION",
    FREEZE_INCEPTION: "FREEZE_INCEPTION",
    REOPEN_INCEPTION: "REOPEN_INCEPTION",
    STABILIZE_INCEPTION: "STABILIZE_INCEPTION",

    CREATE_ELICITATION: "CREATE_ELICITATION",
    UPDATE_ELICITATION: "UPDATE_ELICITATION",
    DELETE_ELICITATION: "DELETE_ELICITATION",
    FREEZE_ELICITATION: "FREEZE_ELICITATION",
    REOPEN_ELICITATION: "REOPEN_ELICITATION",
    STABILIZE_ELICITATION: "STABILIZE_ELICITATION",

    CREATE_ELABORATION: "CREATE_ELABORATION",
    UPDATE_ELABORATION: "UPDATE_ELABORATION",
    DELETE_ELABORATION: "DELETE_ELABORATION",
    FREEZE_ELABORATION: "FREEZE_ELABORATION",
    REOPEN_ELABORATION: "REOPEN_ELABORATION",
    STABILIZE_ELABORATION: "STABILIZE_ELABORATION",

    CREATE_NEGOTIATION: "CREATE_NEGOTIATION",
    UPDATE_NEGOTIATION: "UPDATE_NEGOTIATION",
    DELETE_NEGOTIATION: "DELETE_NEGOTIATION",
    FREEZE_NEGOTIATION: "FREEZE_NEGOTIATION",
    REOPEN_NEGOTIATION: "REOPEN_NEGOTIATION",
    STABILIZE_NEGOTIATION: "STABILIZE_NEGOTIATION",

    CREATE_SPECIFICATION: "CREATE_SPECIFICATION",
    UPDATE_SPECIFICATION: "UPDATE_SPECIFICATION",
    DELETE_SPECIFICATION: "DELETE_SPECIFICATION",
    FREEZE_SPECIFICATION: "FREEZE_SPECIFICATION",
    REOPEN_SPECIFICATION: "REOPEN_SPECIFICATION",
    STABILIZE_SPECIFICATION: "STABILIZE_SPECIFICATION",

    CREATE_VALIDATION: "CREATE_VALIDATION",
    UPDATE_VALIDATION: "UPDATE_VALIDATION",
    DELETE_VALIDATION: "DELETE_VALIDATION",
    FREEZE_VALIDATION: "FREEZE_VALIDATION",
    REOPEN_VALIDATION: "REOPEN_VALIDATION",
    STABILIZE_VALIDATION: "STABILIZE_VALIDATION",

    CREATE_MEETING: "CREATE_MEETING",
    UPDATE_MEETING: "UPDATE_MEETING",
    CANCEL_MEETING: "CANCEL_MEETING",
    SCHEDULE_MEETING: "SCHEDULE_MEETING",
    RESCHEDULE_MEETING: "RESCHEDULE_MEETING",
    START_MEETING: "START_MEETING",
    END_MEETING: "END_MEETING",
    FREEZE_MEETING: "FREEZE_MEETING",
    
    ADD_MEETING_MEMBER: "ADD_MEETING_MEMBER",
    REMOVE_MEETING_MEMBER: "REMOVE_MEETING_MEMBER",
    UPDATE_MEETING_MEMBER: "UPDATE_MEETING_MEMBER",

    DELETE_COMMENT: "DELETE_COMMENT",
    CREATE_COMMENT: "CREATE_COMMENT",
    REPLIED_ON_COMMENT: "REPLIED_ON_COMMENT",
    UPDATE_COMMENT: "UPDATE_COMMENT",
    REQUIREMENT_CREATED: "REQUIREMENT_CREATED",
    REQUIREMENT_UPDATED: "REQUIREMENT_UPDATED",
    REQUIREMENT_DELETED: "REQUIREMENT_DELETED",
    REQUIREMENT_TRANSITIONED_TO_REVIEW: "REQUIREMENT_TRANSITIONED_TO_REVIEW",
    REQUIREMENT_ISSUED: "REQUIREMENT_ISSUED",
    REQUIREMENT_ACCEPTED: "REQUIREMENT_ACCEPTED",
    REQUIREMENT_REJECTED: "REQUIREMENT_REJECTED",
    REQUIREMENT_REVERTED_TO_DRAFT: "REQUIREMENT_REVERTED_TO_DRAFT",
    REQUIREMENT_FEATURE_MAPPED: "REQUIREMENT_FEATURE_MAPPED",
    REQUIREMENT_FEATURE_REMAPPED: "REQUIREMENT_FEATURE_REMAPPED",
    REQUIREMENT_FEATURE_UNMAPPED: "REQUIREMENT_FEATURE_UNMAPPED",
    REQUIREMENT_LINKED: "REQUIREMENT_LINKED",
    REQUIREMENT_DEFERRED: "REQUIREMENT_DEFERRED",
    REQUIREMENT_REVOKED: "REQUIREMENT_REVOKED",
    REQUIREMENT_ASSIGNEE_ASSIGNED: "REQUIREMENT_ASSIGNEE_ASSIGNED",
    REQUIREMENT_ASSIGNEE_UNASSIGNED: "REQUIREMENT_ASSIGNEE_UNASSIGNED",
    REQUIREMENT_STATUS_UPDATED: "REQUIREMENT_STATUS_UPDATED",
    REQUIREMENT_ASSIGNED: "REQUIREMENT_ASSIGNED",
    REQUIREMENT_UNLINKED: "REQUIREMENT_UNLINKED",
    REQUIREMENT_LINK_UPDATED: "REQUIREMENT_LINK_UPDATED",
    REQUIREMENT_COLLABORATOR_REMOVED: "REQUIREMENT_COLLABORATOR_REMOVED",

    // ========== REVIEW NOTES EVENTS ==========
    REVIEW_NOTE_CREATED: "REVIEW_NOTE_CREATED",
    REVIEW_NOTE_UPDATED: "REVIEW_NOTE_UPDATED",
    REVIEW_NOTE_DELETED: "REVIEW_NOTE_DELETED",

    // ========== PHASE ROLE MANAGEMENT EVENTS ==========
    REQUIREMENT_CONTRIBUTOR_ADDED: "REQUIREMENT_CONTRIBUTOR_ADDED",
    REQUIREMENT_CONTRIBUTOR_REMOVED: "REQUIREMENT_CONTRIBUTOR_REMOVED",
    CONTRIBUTOR_ADDED: "CONTRIBUTOR_ADDED",
    CONTRIBUTOR_REMOVED: "CONTRIBUTOR_REMOVED",
    REVIEWER_ADDED: "REVIEWER_ADDED",
    REVIEWER_REMOVED: "REVIEWER_REMOVED",
    APPROVER_ADDED: "APPROVER_ADDED",
    APPROVER_REMOVED: "APPROVER_REMOVED",

    CREATE_IDEA: "CREATE_IDEA",
    UPDATE_IDEA: "UPDATE_IDEA",
    DELETE_IDEA: "DELETE_IDEA",
    LINK_HLF_TO_IDEA: "LINK_HLF_TO_IDEA",
    UNLINK_HLF_FROM_IDEA: "UNLINK_HLF_FROM_IDEA",
    REOPEN_IDEA: "REOPEN_IDEA",
    REVOKE_IDEA: "REVOKE_IDEA",
    ACCEPT_IDEA: "ACCEPT_IDEA",
    REJECT_IDEA: "REJECT_IDEA",
    DEFER_IDEA: "DEFER_IDEA",

    BULK_IMPORT_CREATED: "BULK_IMPORT_CREATED",
    REQUIREMENTS_IMPORTED_IN_BULK: "REQUIREMENTS_IMPORTED_IN_BULK"
  }),

  SERVICE_TRACKER_EVENTS: Object.freeze({
    // ========== INTERNAL CONTROLLER EVENTS ==========
    DELETE_INACTIVE_USERS: "DELETE_INACTIVE_USERS",
    
    // ========== SYNC EVENTS ==========
    SYNC_USER_DATA: "SYNC_USER_DATA", 
    SYNC_ADMIN_DATA: "SYNC_ADMIN_DATA",
    SYNC_MY_DATA: "SYNC_MY_DATA",
    
    // ========== SYSTEM EVENTS ==========
    CREATE_SUPER_ADMIN: "CREATE_SUPER_ADMIN",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
    UPDATE_ADMIN_DETAILS: "UPDATE_ADMIN_DETAILS"
  })
};