// middlewares/admins/field-validation.middleware.js

const { FieldDefinitions } = require("@configs/field-definitions.config");
const { getValidationSet } = require("@utils/field-definition.util");

const validationSets = {
    createProjectValidationSet: getValidationSet(FieldDefinitions.CREATE_PROJECT),
    updateProjectValidationSet: getValidationSet(FieldDefinitions.UPDATE_PROJECT),
    onHoldProjectValidationSet: getValidationSet(FieldDefinitions.ON_HOLD_PROJECT),
    abortProjectValidationSet: getValidationSet(FieldDefinitions.ABORT_PROJECT),
    completeProjectValidationSet: getValidationSet(FieldDefinitions.COMPLETE_PROJECT),
    resumeProjectValidationSet: getValidationSet(FieldDefinitions.RESUME_PROJECT),
    deleteProjectValidationSet: getValidationSet(FieldDefinitions.DELETE_PROJECT),
    archiveProjectValidationSet: getValidationSet(FieldDefinitions.ARCHIVE_PROJECT),
    activateProjectValidationSet: getValidationSet(FieldDefinitions.ACTIVATE_PROJECT),
    changeProjectOwnerValidationSet: getValidationSet(FieldDefinitions.CHANGE_PROJECT_OWNER),
    createStakeholderValidationSet: getValidationSet(FieldDefinitions.CREATE_STAKEHOLDER),
    updateStakeholderValidationSet: getValidationSet(FieldDefinitions.UPDATE_STAKEHOLDER),
    deleteStakeholderValidationSet: getValidationSet(FieldDefinitions.DELETE_STAKEHOLDER),
    createProductRequestValidationSet: getValidationSet(FieldDefinitions.CREATE_PRODUCT_REQUEST),
    updateProductRequestValidationSet: getValidationSet(FieldDefinitions.UPDATE_PRODUCT_REQUEST),
    deleteProductRequestValidationSet: getValidationSet(FieldDefinitions.DELETE_PRODUCT_REQUEST),
    approveProductRequestValidationSet: getValidationSet(FieldDefinitions.APPROVE_PRODUCT_REQUEST),
    rejectProductRequestValidationSet: getValidationSet(FieldDefinitions.REJECT_PRODUCT_REQUEST),
    createScopeValidationSet: getValidationSet(FieldDefinitions.CREATE_SCOPE),
    updateScopeValidationSet: getValidationSet(FieldDefinitions.UPDATE_SCOPE),
    deleteScopeValidationSet: getValidationSet(FieldDefinitions.DELETE_SCOPE),
    createHlfValidationSet: getValidationSet(FieldDefinitions.CREATE_HLF),
    updateHlfValidationSet: getValidationSet(FieldDefinitions.UPDATE_HLF),
    deleteHlfValidationSet: getValidationSet(FieldDefinitions.DELETE_HLF),
    createIdeaValidationSet: getValidationSet(FieldDefinitions.CREATE_IDEA),
    updateIdeaValidationSet: getValidationSet(FieldDefinitions.UPDATE_IDEA),
    deleteIdeaValidationSet: getValidationSet(FieldDefinitions.DELETE_IDEA),
    acceptIdeaValidationSet: getValidationSet(FieldDefinitions.ACCEPT_IDEA),
    rejectIdeaValidationSet: getValidationSet(FieldDefinitions.REJECT_IDEA),
    deferIdeaValidationSet: getValidationSet(FieldDefinitions.DEFER_IDEA),
    reopenIdeaValidationSet: getValidationSet(FieldDefinitions.REOPEN_IDEA),
    revokeIdeaValidationSet: getValidationSet(FieldDefinitions.REVOKE_IDEA),
    createProductVisionValidationSet: getValidationSet(FieldDefinitions.CREATE_PRODUCT_VISION),
    updateProductVisionValidationSet: getValidationSet(FieldDefinitions.UPDATE_PRODUCT_VISION),
    deleteProductVisionValidationSet: getValidationSet(FieldDefinitions.DELETE_PRODUCT_VISION),
    commentEntityValidationSet: getValidationSet(FieldDefinitions.COMMENT_ENTITY),
    createCommentValidationSet: getValidationSet(FieldDefinitions.CREATE_COMMENT),
    updateCommentValidationSet: getValidationSet(FieldDefinitions.UPDATE_COMMENT),
    deleteCommentValidationSet: getValidationSet(FieldDefinitions.DELETE_COMMENT),
    createInceptionValidationSet: getValidationSet(FieldDefinitions.CREATE_INCEPTION),
    updateInceptionValidationSet: getValidationSet(FieldDefinitions.UPDATE_INCEPTION),
    deleteInceptionValidationSet: getValidationSet(FieldDefinitions.DELETE_INCEPTION),
    createElicitationValidationSet: getValidationSet(FieldDefinitions.CREATE_ELICITATION),
    updateElicitationValidationSet: getValidationSet(FieldDefinitions.UPDATE_ELICITATION),
    deleteElicitationValidationSet: getValidationSet(FieldDefinitions.DELETE_ELICITATION),
    createElaborationValidationSet: getValidationSet(FieldDefinitions.CREATE_ELABORATION),
    updateElaborationValidationSet: getValidationSet(FieldDefinitions.UPDATE_ELABORATION),
    deleteElaborationValidationSet: getValidationSet(FieldDefinitions.DELETE_ELABORATION),
    createNegotiationValidationSet: getValidationSet(FieldDefinitions.CREATE_NEGOTIATION),
    updateNegotiationValidationSet: getValidationSet(FieldDefinitions.UPDATE_NEGOTIATION),
    deleteNegotiationValidationSet: getValidationSet(FieldDefinitions.DELETE_NEGOTIATION),
    createSpecificationValidationSet: getValidationSet(FieldDefinitions.CREATE_SPECIFICATION),
    updateSpecificationValidationSet: getValidationSet(FieldDefinitions.UPDATE_SPECIFICATION),
    deleteSpecificationValidationSet: getValidationSet(FieldDefinitions.DELETE_SPECIFICATION),
    createValidationValidationSet: getValidationSet(FieldDefinitions.CREATE_VALIDATION),
    updateValidationValidationSet: getValidationSet(FieldDefinitions.UPDATE_VALIDATION),
    deleteValidationValidationSet: getValidationSet(FieldDefinitions.DELETE_VALIDATION),
    createMeetingValidationSet: getValidationSet(FieldDefinitions.CREATE_MEETING),
    updateMeetingValidationSet: getValidationSet(FieldDefinitions.UPDATE_MEETING),
    cancelMeetingValidationSet: getValidationSet(FieldDefinitions.CANCEL_MEETING),
    scheduleMeetingValidationSet: getValidationSet(FieldDefinitions.SCHEDULE_MEETING),
    rescheduleMeetingValidationSet: getValidationSet(FieldDefinitions.RESCHEDULE_MEETING),
    addParticipantValidationSet: getValidationSet(FieldDefinitions.ADD_PARTICIPANT),
    updateParticipantValidationSet: getValidationSet(FieldDefinitions.UPDATE_PARTICIPANT),
    removeParticipantValidationSet: getValidationSet(FieldDefinitions.REMOVE_PARTICIPANT),
    createOrgProjectRequestValidationSet: getValidationSet(FieldDefinitions.CREATE_ORG_PROJECT_REQUEST),
    approveOrgProjectRequestValidationSet: getValidationSet(FieldDefinitions.APPROVE_ORG_PROJECT_REQUEST),
    rejectOrgProjectRequestValidationSet: getValidationSet(FieldDefinitions.REJECT_ORG_PROJECT_REQUEST),
    updateOrgProjectRequestValidationSet: getValidationSet(FieldDefinitions.UPDATE_ORG_PROJECT_REQUEST),

    // ── Requirement Operations ────────────────────────────────────────────────
    createRequirementValidationSet: getValidationSet(FieldDefinitions.CREATE_REQUIREMENT),
    updateRequirementValidationSet: getValidationSet(FieldDefinitions.UPDATE_REQUIREMENT),
    deleteRequirementValidationSet: getValidationSet(FieldDefinitions.DELETE_REQUIREMENT),
    transitionRequirementToReviewValidationSet: getValidationSet(FieldDefinitions.TRANSITION_REQUIREMENT_TO_REVIEW),
    issueRequirementValidationSet: getValidationSet(FieldDefinitions.ISSUE_REQUIREMENT),
    acceptRequirementValidationSet: getValidationSet(FieldDefinitions.ACCEPT_REQUIREMENT),
    rejectRequirementValidationSet: getValidationSet(FieldDefinitions.REJECT_REQUIREMENT),
    assignRequirementValidationSet: getValidationSet(FieldDefinitions.ASSIGN_REQUIREMENT),
    unassignRequirementValidationSet: getValidationSet(FieldDefinitions.UNASSIGN_REQUIREMENT),
    revokeRequirementValidationSet: getValidationSet(FieldDefinitions.REVOKE_REQUIREMENT),
    deferRequirementValidationSet: getValidationSet(FieldDefinitions.DEFER_REQUIREMENT),
    linkRequirementToHlfValidationSet: getValidationSet(FieldDefinitions.LINK_REQUIREMENT_TO_HLF),
    revertToDraftValidationSet: getValidationSet(FieldDefinitions.REVERT_TO_DRAFT),
    assignCollaboratorValidationSet: getValidationSet(FieldDefinitions.ASSIGN_COLLABORATOR),
    unassignCollaboratorValidationSet: getValidationSet(FieldDefinitions.UNASSIGN_COLLABORATOR),
    updateRequirementToHlfValidationSet: getValidationSet(FieldDefinitions.UPDATE_REQUIREMENT_TO_HLF),
    unlinkRequirementToHlfValidationSet: getValidationSet(FieldDefinitions.UNLINK_REQUIREMENT_TO_HLF),

    phaseRoleActionValidationSet: getValidationSet(FieldDefinitions.PHASE_ROLE_ACTION),
};

module.exports = { validationSets };